/**
 * The signed-in app's own words: the sidebar, the phone bar, and the pages the sidebar opens (Overview, Activity,
 * Settings). An agent is what the owner sees; "desk" is only the contract's name in code.
 */
export const appCopy = {
  /** The app's navigation, in the reference wallet's order: your money first, then your agents, then Discover. */
  nav: {
    brand: 'SHIJIMA',
    tagline: 'AI AGENTS · ROBINHOOD',
    motto: 'Shijima · AI agents that trade Stock Tokens 24/7 on Robinhood Chain',
    wallet: 'Wallet',
    activity: 'Activity',
    send: 'Send',
    receive: 'Receive',
    fund: 'Fund',
    withdraw: 'Withdraw',
    bridge: 'Bridge',
    evidence: 'Evidence',
    agents: 'Agents',
    markets: 'Markets',
    strategies: 'Strategies',
    reels: 'Reels',
    live: 'Live',
    settings: 'Settings',
    newAgent: 'New agent',
    more: 'More',
    moreTitle: 'Everything else',
    groups: {
      money: 'Your money',
      agents: 'Your agents',
      discover: 'Discover',
      move: 'Move',
      account: 'Account',
    },
    details: {
      send: 'From your wallet to any address',
      receive: 'Your address and your agents’, with QR codes',
      fund: 'Any token, from any chain, into an agent',
      withdraw: 'From an agent back to your wallet',
      bridge: 'In from Base, Arbitrum, Ethereum or BNB, or out',
      evidence: 'Every decision and move, with its proof',
      agents: 'Every live agent, and copying one',
      markets: 'Stock Tokens, open and closed hours',
      strategies: 'Twenty baskets to start from',
      reels: 'Decisions and stocks, one at a time',
      live: 'The live numbers, on mainnet',
      settings: 'Connections, access, gas',
    },
    home: 'Shijima home',
  },

  sidebar: {
    aria: 'Shijima',
    home: 'Overview',
    groups: { you: 'You', agents: 'Your agents', discover: 'Discover' },
    overview: 'Overview',
    needsYou: 'Needs you',
    activity: 'Activity',
    newAgent: 'New agent',
    markets: 'Markets',
    liveAgents: 'Live agents',
    strategies: 'Strategies',
    reels: 'Reels',
    settings: 'Settings',
    landing: 'Shijima home',
    toggle: 'Toggle sidebar',
    close: 'Close sidebar',
    copying: (leader: string) => `copying ${leader}`,
    noValue: 'not valued yet',
    status: {
      running: 'Running',
      needsYou: 'Needs you',
      paused: 'Paused',
      practice: 'Practice',
      closed: 'Closed',
    },
    signedOut: {
      title: 'Your agents live here',
      body: 'Connect a wallet to start an agent, or copy one that is already running.',
    },
    runsOn: 'Runs on OpenServ',
    reasoning: 'decisions by SERV Reasoning',
  },

  wallet: {
    aria: 'Your wallet',
    usdg: 'USDG',
    gas: 'Gas',
    /** Signatures, not trades: the agent's trades are paid by Shijima. */
    gasLeft: (n: number) => (n >= 100 ? '100+ signatures' : `~${n} signature${n === 1 ? '' : 's'}`),
    gasNone: 'No gas yet',
    gasTitle:
      'The ETH in your wallet pays for what you sign yourself: creating an agent, adding money, withdrawing. ' +
      "Your agent's trades are paid by Shijima, about 5¢ each.",
    getGas: 'Get gas',
    reading: 'reading…',
  },

  live: {
    badge: 'Live on Robinhood Chain mainnet',
    short: 'Live on mainnet',
    block: (n: string) => `block ${n}`,
    title: 'The network Shijima trades on, read from your browser right now.',
  },

  bottomBar: {
    aria: 'App navigation',
    overview: 'Overview',
    agents: 'Agents',
    markets: 'Markets',
    activity: 'Activity',
    menu: 'Menu',
  },

  topBar: {
    ask: 'Ask Shijima',
  },

  ask: {
    button: 'Ask Shijima',
    title: (name: string) => `Ask ${name}`,
    note: 'Ask what it holds and why, or tell it what to change. It shows you a card, and nothing changes until you confirm.',
    noAgent: 'Start an agent first, then talk to it here from any page.',
    close: 'Close the chat',
  },

  overview: {
    meta: 'Overview',
    kicker: 'Your agents, together',
    title: 'Overview',
    stats: {
      total: 'All your agents hold',
      totalNone: 'Not valued yet',
      day: 'In the last day',
      dayNone: 'A day of history is needed',
      agents: 'Agents',
      agentsNote: (running: number, practice: number) => `${running} trading · ${practice} in practice`,
      needs: 'Needs you',
      needsNone: 'Nothing waits on you',
      needsSome: (n: number) => `${n} request${n === 1 ? '' : 's'} to answer`,
    },
    chart: 'What they hold together',
    chartNote: 'Every agent added up, hour by hour. Money you add counts; it is not gain.',
    agentsTitle: 'Your agents',
    open: 'Open',
    noDecision: 'No decision yet. Its first look is on the next five-minute mark.',
    needsTitle: 'Waiting for your answer',
    needsEmpty: 'Nothing is waiting. Your agents act inside your limits and ask for anything larger.',
    answer: 'Answer',
    connectTitle: 'Connections',
    telegram: 'Telegram',
    openserv: 'OpenServ',
    connected: 'connected',
    notConnected: 'connect',
    connectBody: 'Approvals, trades and alerts in Telegram. Your agent in your own OpenServ workspace.',
    empty: {
      title: 'Start your first agent',
      body: 'An agent is an account on Robinhood Chain that only you can withdraw from, and an AI that trades it inside limits you set. Make one, or copy one that is already running.',
      create: 'Create an agent',
      copy: 'Copy an agent',
    },
  },

  activity: {
    meta: 'Activity',
    kicker: 'Every agent, every decision',
    title: 'Activity',
    sub: 'Recent decisions from every agent, including quiet checks, and what waits on you. Each links to its record and its proof.',
    tabs: { all: 'All', needs: 'Needs you', trades: 'Trades' },
    quiet: 'Hide quiet checks',
    noneAll: 'No decisions yet. Your agents look every five minutes and write down each decision here.',
    noneNeeds: 'Nothing waits on you. Your agents act inside your limits and ask for anything larger.',
    noneTrades: 'No trades yet. Practice decisions show under All.',
    practice: 'practice',
    open: 'Open',
    signIn: 'Sign in to see what your agents did.',
    waiting: (n: number) => `${n} WAITING`,
    upToDate: 'UP TO DATE',
    stats: {
      decisions: 'Decisions',
      decisionsNote: 'In this recent feed',
      trades: 'Trades',
      tradesNote: 'Real trades in this feed',
      practice: 'Practice',
      practiceNote: 'Decided, nothing sent',
      needs: 'Need you',
      needsNote: 'Waiting on your answer',
    },
    emptyTitles: { all: 'No decisions yet', needs: 'Nothing waits on you', trades: 'No trades yet' },
    emptyBodies: {
      all: 'Your agents look every five minutes and write down each decision here, with why they made it.',
      needs: 'Your agents act inside your limits and ask for anything larger.',
      trades: 'Practice decisions show under All.',
    },
    emptyCta: 'Create an agent',
    emptyAll: 'See every decision',
    sides: { buy: 'BUY', sell: 'SELL', sweep: 'SAVE', redeem: 'REDEEM' } as Record<string, string>,
  },

  settings: {
    meta: 'Settings',
    kicker: 'Your account',
    title: 'Settings',
    nav: {
      connections: 'Connections',
      wallet: 'Wallet & gas',
      agents: 'Agents & access',
      disclosure: 'What you agreed to',
    },
    openserv: {
      title: 'OpenServ',
      none: 'Workspaces link to an agent. Create one first.',
    },
    access: {
      mode: 'Mode',
      trades: 'Can trade',
      trader: (addr: string) => `Shijima · ${addr}`,
      removed: 'Nobody. You removed Shijima',
      session: 'Session key',
      sessionUntil: (addr: string, until: string) => `${addr} · until ${until}`,
      noSession: 'None',
      withdraw: 'Can withdraw',
      onlyYou: 'Only your wallet',
      closed: 'Closed',
    },
    none: 'No agents yet.',
    agentSettings: 'Agent settings',
    sub: 'Your account, connections, who can act for your agents, and what you agreed to.',
    groups: {
      account: 'Account',
      connections: 'Connections',
      access: 'Agents & access',
      agreed: 'What you agreed to',
    },
    address: 'Your wallet',
    gas: 'Gas for what you sign',
    getGas: 'Get gas',
    verify: {
      title: 'Verify it yourself',
      badge: 'ON CHAIN',
      rows: [
        'Every decision, with its fingerprint',
        'The live numbers on mainnet',
        'The contracts, on Blockscout',
      ],
      open: 'Open ›',
    },
    realMoney:
      'Real money, on Robinhood Chain mainnet. Your agents trade inside the limits you set; only your wallet can take money out.',
    disconnect: 'Disconnect',
  },

  agentPage: {
    by: (owner: string) => `by ${owner}`,
    yours: 'Your agent',
    settings: 'Agent settings',
    decision: {
      title: 'Latest decision',
      none: 'No decision yet. It looks every five minutes and writes down what it decides here, first.',
      action: (side: string, amount: string | null, symbol: string) =>
        side === 'buy'
          ? `Buy ${amount ? `${amount} of ` : ''}${symbol}`
          : side === 'sell'
            ? `Sell ${amount ? `${amount} of ` : ''}${symbol}`
            : `${side} ${symbol}`,
      sure: (pct: number) => `${pct}% sure`,
      sureTitle: 'How sure the AI said it was. The account’s limits apply whatever it says.',
      options: 'The options it weighed',
      tx: (hash: string) => `On chain · ${hash}`,
      sentNotConfirmed: (hash: string) => `Sent · ${hash} · waiting for the network`,
      practice: 'Practice: decided for real, nothing sent',
      nothingSent: 'Nothing was sent',
      sealed: (hash: string) => `Fingerprinted on chain · ${hash}`,
      open: 'Full record',
      serv: 'Reasoned with SERV',
      servTitle:
        'This call was made by a model through OpenServ’s SERV Reasoning. See the same model with and without it.',
      emptyTitle: 'No decision yet',
      emptyQuiet:
        'Every look so far found nothing to do: its stocks are near their targets, or too small to buy. The first real decision lands here.',
      emptyNew: 'It looks every five minutes. Its first real decision lands here, with why it made it.',
      firstLook: (when: string) => `Next look ${when}`,
    },
    /** What the agent is doing right now, in one card under the header. */
    status: {
      title: 'Right now',
      lastLook: 'Last look',
      nextLook: 'Next look',
      market: 'US market',
      notYet: 'not yet',
      inTime: (t: string) => `in ${t}`,
      now: 'any moment',
      closed: { title: 'Closed', body: 'This agent is closed. It no longer looks or trades.' },
      onboarding: {
        title: 'Getting ready',
        body: 'Its account is being set up. It starts looking once its money lands.',
      },
      paused: (own: boolean) => ({
        title: own ? 'Paused by you' : 'Paused by its owner',
        body: 'It is not looking or trading. What it holds stays where it is.',
      }),
      stopped: {
        title: 'Stopped by the loss limit',
        body: 'Its value fell past the loss limit, so it stopped trading. Nothing moves until it is restarted.',
      },
      attention: {
        title: 'Needs attention',
        body: 'It stopped until its owner looks at what went wrong.',
      },
      noMoney: {
        title: 'Waiting for money',
        body: 'It has nothing to look after yet. Once money lands, it starts buying on its next look.',
      },
      tooSmall: (cash: string) => ({
        title: 'Holding cash',
        body: `It holds ${cash}, but a required buy or the cash available above its reserve is below the minimum trade.`,
      }),
      notQualified: { title: 'No trade qualified' },
      checks: (count: number) =>
        `${count.toLocaleString('en-US')} checks completed. Quiet looks do not each create a decision.`,
      waiting: (side: string, name: string, when: string) => ({
        title: `Waiting to ${side === 'sell' ? 'sell' : 'buy'} ${name}`,
        body: `It chose to wait for a better moment, and looks at it again ${when}.`,
      }),
      due: (name: string) => ({
        title: `Rebalancing ${name}`,
        body: `${name} is off its target. On its next look, it reviews timing, trading conditions and limits before acting.`,
      }),
      watching: (n: number, drift: string, practice: boolean) => ({
        title: practice ? 'Practising' : 'Watching',
        body: `${n} ${n === 1 ? 'stock' : 'stocks'}, each within ${drift} of its target. It acts when one drifts further${practice ? ', deciding for real and spending nothing' : ''}.`,
      }),
    },
    record: (better: number, graded: number) =>
      graded === 0 ? 'Timing not graded yet' : `${better} of ${graded} timing calls beat the alternative`,
    portfolio: {
      title: 'Portfolio',
      notYet: 'Not valued yet. Its first valuation comes with its first look, within five minutes.',
      valued: (ago: string) => `valued ${ago}`,
      sinceStart: 'since the money went in',
      noHistory: 'One valuation so far. The chart starts with the second.',
      holdings: 'What it holds',
      cash: 'Cash (USDG)',
      inSavings: (amount: string) => `${amount} earning in savings`,
      stockPage: (symbol: string) => `${symbol} price, reference and reports`,
      legendNow: 'Now',
      legendTarget: 'Target',
      barLabel: (name: string, now: string, target: string) => `${name}: ${now} now, target ${target}`,
    },
    activity: {
      title: 'Activity',
      ask: 'Ask Shijima',
      all: 'Every decision',
    },
    tooSmall: {
      title: 'Your agent can’t buy yet.',
      body: (cash: string, more: string) =>
        `It holds ${cash}, but the required buy or cash available above its reserve is below the 20¢ minimum. Adding at least ${more} is estimated to make one buy large enough while keeping your cash target. Prices can change; timing and limits still apply.`,
      add: (more: string) => `Add ${more}`,
      plan: 'Change the plan',
      meter: (buy: string, min: string) => `Largest buy ${buy} · smallest trade ${min}`,
    },
    money: {
      title: 'Agent account',
      address: 'Its address on Robinhood Chain',
      addressNote:
        'Send USDG on Robinhood Chain to this address from any wallet or exchange. Only the owner can take it out.',
      copy: 'Copy',
      copied: 'Copied',
      qr: 'QR code',
      hideQr: 'Hide QR',
      gasBody: 'Shijima pays each trade’s network fee, about 5¢. You pay only for what you sign.',
      explorer: 'Blockscout',
      cash: 'Cash',
      savings: 'Savings',
      stocks: 'Stocks',
      total: 'Total',
      asOf: (when: string) => `Last checked ${when}`,
      receive: 'Receive',
      split: 'Where its money is',
      empty: 'No money in it yet.',
    },
  },

  agents: {
    meta: 'Agents',
    kicker: 'Live on Robinhood Chain',
    title: 'Agents',
    intro:
      'Every agent here is an account on the chain with an AI working it inside hard limits. Watch any of them, or copy one: your own agent then makes the same moves with your own money, and only you can take it out.',
    yours: 'Your agents',
    live: 'Live agents',
    none: {
      title: 'You have no agent yet',
      body: 'Make one from a strategy, or copy one of the agents below. Either way it is your own account, and only you can withdraw from it.',
      create: 'Create an agent',
      copy: 'Copy an agent',
    },
    noneShared: 'No agent is shared yet. Yours can be the first: turn sharing on in its settings.',
    columns: { agent: 'Agent', latest: 'Latest decision', value: 'Holds', record: 'Track record' },
    record: (better: number, graded: number) =>
      graded === 0 ? 'Not graded yet' : `${better} of ${graded} timing calls beat the alternative`,
    recordTitle:
      'Each timing call is graded when the US market reopens: was acting (or waiting) better than the other choice? Only real grades are counted.',
    followers: (n: number) => (n === 0 ? 'No one copies it yet' : `${n} ${n === 1 ? 'copies' : 'copy'} it`),
    copy: 'Copy',
    watch: 'Watch',
    practice: 'Practice',
    liveMode: 'Trading',
    noDecision: 'No decision yet',
    newAgent: 'New agent',
    newAgentBody: 'Pick a strategy and an amount',
    needsYou: (n: number) => `${n} waiting for you`,
    rank: (n: number) => `#${n}`,
    looking: 'Looking every 5 min',
    notRunning: 'Not running',
    day: '24h',
    holds: 'Holds',
    cash: 'Cash',
    fee: (amount: string) => `Copy fee ${amount}`,
    free: 'Free to copy',
    closedToCopy: 'Not open to copying',
    stocks: (n: number) => `${n} ${n === 1 ? 'stock' : 'stocks'}`,
    emptyShared: {
      title: 'No shared agents yet',
      body: 'When an owner turns sharing on, their agent appears here with what it holds, how it is doing and every decision it makes. Yours can be the first.',
      create: 'Create an agent',
    },
  },

  copy: {
    button: 'Copy this agent',
    dialog: {
      eyebrow: 'Copy trading',
      title: (name: string) => `Copy ${name}`,
      how: [
        'You get your own agent: your own account on Robinhood Chain, with your own money. Only you can take it out.',
        'Every time this agent trades, yours makes the same move as a share of its own value. If it puts 12% of its money into Nvidia, yours puts 12% of yours.',
        'Your own limits still apply to every copy. A move your agent cannot make is written down as a missed copy, with the reason.',
        'Pause or stop at any time. What your agent holds stays yours.',
      ],
      fee: 'One-time copy fee',
      free: 'Free to copy',
      split: (creator: string, shijima: string) => `${creator} to the creator · ${shijima} to Shijima`,
      trading:
        'Trading on Shijima itself is free. The network fee for each trade is paid by Shijima, about 5¢.',
      signIn: 'Sign in with email or your wallet to copy. Your agent belongs to your account’s wallet.',
      continue: 'Continue: set up your agent',
      yours: 'This is your own agent. Others can copy it once you allow it in its settings.',
      settings: 'Open its settings',
    },
    studio: {
      banner: (name: string) => `Copying ${name}`,
      bannerBody:
        'This agent starts with its mix. Choose how much to put in and your own limits, then create it. After that you pay the copy fee, if there is one, and it starts copying.',
    },
    finish: {
      title: (name: string) => `Last step: start copying ${name}`,
      body: 'Your agent exists. Pay the one-time fee to its creator, then the copying starts with its next trade.',
      payCreator: (amount: string) => `Pay ${amount} to the creator`,
      payShijima: (amount: string) => `Pay ${amount} to Shijima`,
      paid: 'Paid',
      start: 'Start copying',
      started: 'Copying. Your agent will follow its next trade.',
      open: 'Open your agent',
      waiting: 'Waiting for the network…',
      rejected: 'The wallet did not send it. Nothing was paid; try again.',
    },
    header: {
      copying: (name: string) => `Copying ${name}`,
      paused: (name: string) => `Copying ${name} · paused`,
      pause: 'Pause',
      resume: 'Resume',
      stop: 'Stop copying',
    },
    settings: {
      title: 'Let others copy this agent',
      body: 'Anyone can then start their own agent that makes the same moves as this one, with their own money. They pay you a one-time fee, and Shijima keeps 20% of it. You never touch their money, and they never touch yours.',
      on: 'Others can copy it',
      off: 'Not open to copying',
      fee: 'One-time fee, in dollars ($0 to $5)',
      save: 'Save',
      saved: 'Saved',
      followers: 'Who copies it',
      noFollowers: 'No one copies it yet.',
      earned: (amount: string) => `${amount} in fees so far`,
    },
    refused: {
      missing: 'That agent is not shared, so it cannot be copied.',
      closed: 'That agent is closed.',
      notCopyable: 'Its owner has not opened it to copying.',
      noStrategy: 'That agent has no strategy yet.',
      signIn: 'Sign in with email or your wallet first.',
      notYours: 'That is not your agent.',
      own: 'You cannot copy your own agent.',
      feeNotSeen: 'The fee transfer was not found on chain yet. Wait a moment and try again.',
      feeRange: 'The fee must be between $0 and $5.',
      failed: 'That did not work. Nothing was changed; try again.',
    },
  },

  openserv: {
    title: 'OpenServ',
    tagline: 'Your agent, inside your own OpenServ workspace.',
    what: 'Linked, your workspace can talk to your agent, ask what it holds and why, and, if you allow it, ask it to look now. It can never move money: anything that would is sent back here for your signature.',
    steps: {
      add: {
        title: 'Add Shijima to OpenServ',
        body: 'Open Shijima on the OpenServ platform and add it to a workflow in your workspace.',
        cta: 'Open Shijima on OpenServ',
        pending: 'Listed on OpenServ; public once their review approves it.',
      },
      link: {
        title: 'Link your workspace',
        body: 'Make a one-time code and send it to Shijima in your workspace chat.',
        make: 'Make a link code',
        making: 'Making…',
        send: 'Send this in your OpenServ workspace:',
        copy: 'Copy',
        copied: 'Copied',
        expires: (left: string) => `Works once, for ${left}.`,
        expired: 'That code has expired. Make a new one.',
        waiting: 'Waiting for your workspace to send it…',
      },
      push: {
        title: 'Send decisions to your workspace',
        body: 'Paste a webhook trigger URL from your OpenServ workspace, and every decision your agent makes starts that workflow.',
        placeholder: 'https://api.openserv.ai/webhooks/trigger/…',
        save: 'Save',
        remove: 'Remove',
        on: 'Decisions go to this workspace.',
      },
    },
    linkedTitle: 'Linked workspaces',
    none: 'No workspace linked yet.',
    workspace: (name: string | null) => name ?? 'A workspace',
    since: (when: string) => `linked ${when}`,
    allowChecks: 'Let it ask for a look now',
    allowChecksNote:
      'Its agents can then wake yours. Your limits still decide; it can never withdraw or raise them.',
    unlink: 'Unlink',
    options: 'Options',
    linkedCount: (n: number) => (n === 1 ? '1 workspace linked' : `${n} workspaces linked`),
    notLinked: 'Not linked yet',
    credit: 'Runs on OpenServ · decisions by SERV Reasoning',
  },

  catalog: {
    meta: 'Strategies',
    kicker: 'Twenty ways to start',
    title: 'Strategies',
    intro:
      'A strategy is a basket of Stock Tokens with a share for each, and some cash. Pick one to start your own agent; it keeps the basket on plan around the clock, inside limits you set. Every token here trades in a deep enough pool on Robinhood Chain, checked on mainnet.',
    all: 'All',
    tags: {
      broad: 'Broad',
      tech: 'Tech',
      ai: 'AI',
      commodities: 'Oil & metals',
      safe: 'Safer',
      bold: 'Bold',
    } as Record<string, string>,
    start: 'Start an agent with this',
    running: (n: number) =>
      n === 0 ? 'No agent runs it yet' : `${n} agent${n === 1 ? '' : 's'} run${n === 1 ? 's' : ''} it`,
    own: 'Or build your own basket',
    notAdvice: 'Past returns are shown, never promised. Nothing here is advice.',
  },

  livePage: {
    meta: 'Live on mainnet',
    kicker: 'Robinhood Chain · chain 4663',
    title: 'Live on mainnet, and you can check every number',
    intro:
      'Shijima runs on Robinhood Chain mainnet with real money. Every count here comes from the record, and every transaction opens on Blockscout.',
    stats: {
      agents: 'Agents',
      agentsNote: (trading: number) => `${trading} trading real money`,
      followers: 'Copying an agent',
      trades: 'Confirmed trades',
      moved: (usd: string) => `${usd} of USDG moved`,
      checkpoints: 'Records fingerprinted on chain',
      serv: 'SERV Reasoning calls',
      runs: 'OpenServ workflow runs',
    },
    latestTitle: 'The latest transactions',
    latestNone: 'No confirmed transaction yet.',
    kinds: {
      buy: 'Buy',
      sell: 'Sell',
      checkpoint: 'Fingerprint',
      sweep: 'To savings',
      redeem: 'From savings',
    } as Record<string, string>,
    revenueTitle: 'Revenue',
    revenueBody:
      'Trading on Shijima is free. When someone copies an agent, they pay its creator a one-time fee they saw first; Shijima keeps 20% of it.',
    creators: 'Earned by creators',
    shijima: 'Earned by Shijima',
    copies: (n: number) => `${n} paid ${n === 1 ? 'copy' : 'copies'}`,
    contractsTitle: 'The contracts',
    factory: 'Agent factory',
    implementation: 'Agent account (every agent is a copy of this)',
    operator: 'Shijima’s operator (trades inside each agent’s limits, pays the gas)',
  },

  credit: {
    line: 'Shijima’s agent runs on OpenServ, and every timing call is made with SERV Reasoning.',
    compare: 'The same model, with and without SERV',
    live: 'Live on mainnet: every number, checked',
  },

  receive: {
    title: 'Or send it from anywhere',
    copy: (addr: string) => `Copy ${addr}`,
    copied: 'Copied',
    warn: 'Send only USDG, and only on Robinhood Chain. It lands in this agent; only you can take it out.',
  },

  carousel: {
    index: 'Live',
    title: 'Agents at work, right now',
    desc: 'Each is a real account on Robinhood Chain mainnet with an AI working it. Open one to see every decision, or copy it.',
    aria: 'Live agents, scroll sideways',
    all: 'Every agent',
    prev: 'Previous agents',
    next: 'Next agents',
    practice: 'Practice',
    live: 'Trading live',
    copy: 'Copy this agent',
    noDecision: 'Its first decision is on the way.',
    create: {
      label: 'Your agent',
      title: 'Start your own, from $1',
      body: 'Pick one of twenty strategies, put in USDG, and your agent keeps it on plan around the clock. A few people get their first $1 free.',
      cta: 'Create an agent',
    },
    how: {
      label: 'Copying',
      title: 'Copy an agent, keep your own keys',
      body: 'Your own agent makes the same moves as the one you copy, sized to your money and held to your limits. Only you can take it out. Stop any time.',
      cta: 'How it works',
    },
  },

  notFound: {
    meta: 'Not found',
    code: '404',
    title: 'Nothing here but the quiet',
    body: 'We could not find this page or record. Agent decisions are public during the beta; you do not need to sign in to read them. Open Live agents to find the record you need.',
    didYouMean: 'Did you mean',
    home: 'Back to the start',
    markets: 'Markets',
    agents: 'Live agents',
  },

  error: {
    title: 'Something broke on our side',
    body: 'This page failed to load. Your money is not affected: it sits in your agent’s account on the chain, and only you can withdraw it.',
    retry: 'Try again',
    home: 'Back to the start',
  },
} as const
