/**
 * Money moving: into an agent, out of it, from your wallet to anyone, across chains, and a dollar of gas. Every
 * ending the owner can meet has its own honest line, in dollars: done, nothing sent, approval given but nothing
 * moved, on its way, and may have been sent.
 *
 * Also the words of the money screens: Wallet, Receive and Evidence, and the access card.
 */
export const moneyCopy = {
  kinds: {
    fund: 'Add money',
    withdraw: 'Withdraw',
    sell_some: 'Sell one stock',
    send: 'Send',
    bridge_in: 'Add money from another chain',
    bridge_out: 'Bridge out',
    get_gas: 'Get gas',
  },
  endings: {
    signing: 'Waiting for your wallet.',
    done: (amount: string) => `Done: ${amount} moved.`,
    nothing_sent: 'Nothing was sent. Your money has not moved.',
    approved_only:
      'The approval went through, but nothing moved. You can try again; the approval is for this amount only.',
    on_its_way: (amount: string) => `On its way: ${amount}. Relay usually delivers in under a minute.`,
    may_have_been_sent:
      'It may have been sent. We could not read the result in time. Check the explorer link before trying again.',
  },
  steps: {
    approve: (symbol: string, amount: string) => `Approve exactly ${amount} of ${symbol}`,
    transferIn: (amount: string) => `Move ${amount} into the agent`,
    swapIn: (from: string, to: string) => `Swap ${from} to ${to} into the agent`,
    send: (amount: string) => `Send ${amount}`,
    relay: (step: string) => `Relay: ${step}`,
    gas: (amount: string) => `Swap ${amount} of USDG to ETH for gas`,
  },
  lines: {
    youSend: (amount: string) => `You send ${amount}`,
    agentGets: (amount: string) => `About ${amount} of USDG lands in the agent`,
    agentGetsAsIs: (amount: string) => `It goes in as it is, worth about ${amount}`,
    atLeast: (amount: string) => `At least ${amount}, or nothing moves`,
    youGet: (amount: string) => `You receive about ${amount}`,
    cost: (amount: string) => `Cost, network and Relay together: about ${amount}`,
    networkFee: (amount: string) => `Network fee: about ${amount}`,
    takes: (seconds: number) =>
      `Takes about ${seconds < 60 ? `${Math.max(1, seconds)} second${seconds <= 1 ? '' : 's'}` : `${Math.round(seconds / 60)} minute${Math.round(seconds / 60) === 1 ? '' : 's'}`}`,
    quoteFresh: 'The price holds for 60 seconds; after that it is checked again.',
  },
  refusals: {
    signIn: 'Sign in with your wallet first.',
    notYourAgent: 'That is not your agent.',
    minimum: 'The smallest amount is $1.',
    amount: 'Enter an amount.',
    notEnough: (held: string) => `Your wallet holds ${held}, less than that.`,
    noGas:
      'Your wallet has no ETH on Robinhood Chain for the network fee. Bring a little from another chain, or claim the free $1, which includes some.',
    unknownToken: 'That token is not one this app moves.',
    unknownChain: 'That chain is not one Relay can bring money from.',
    noEthToAgent: 'An agent cannot hold ETH. It arrives as USDG instead.',
    badAddress: 'That is not a valid address.',
    tokenContract: 'That address is a token contract, not a wallet. Money sent there is lost.',
    toYourAgent: 'That is one of your agents. Use Add money instead, so it is recorded as money in.',
    refusedByChain: 'The chain would refuse this right now. Nothing was sent.',
    quote: (why: string) => `No price for that right now: ${why}`,
    expired: 'That price has expired. Here is a fresh one.',
    needOrigin:
      'You have no ETH on Robinhood Chain to pay for a swap. Bring gas from another chain instead: pick where it comes from.',
  },
  chart: {
    tookOut: (amount: string) => `You took out ${amount}`,
    added: (amount: string) => `You added ${amount}`,
    addedFrom: (amount: string, chain: string) => `You added ${amount} from ${chain}`,
    netOfMoney: 'Change after money in and out',
  },
  checked: {
    justNow: 'checked just now',
    ago: (when: string) => `checked ${when}`,
  },

  signedOut: {
    title: 'Shijima',
    welcome: 'Your wallet, and your agents',
    body: 'Connect the wallet you hold money in. Signing in costs nothing and moves nothing.',
    note: 'Only your wallet can take money out of your agents. Not us, and not the agent.',
  },

  receive: {
    meta: 'Receive',
    title: 'Receive',
    sub: 'Share your wallet’s address, or one of your agents’, to be paid on Robinhood Chain.',
    tabWallet: 'Your wallet',
    walletLabel: 'YOUR WALLET ON ROBINHOOD CHAIN',
    agentLabel: (name: string) => `${name.toUpperCase()} · AGENT ACCOUNT`,
    walletCaption: 'Scan to pay your wallet on Robinhood Chain',
    agentCaption: 'Scan to pay this agent on Robinhood Chain',
    copy: 'Copy address',
    copied: 'Copied',
    explorer: 'View on Blockscout',
    walletCalloutTitle: 'Robinhood Chain only.',
    walletCallout:
      'USDG, ETH and Stock Tokens sent here land in your own wallet. From there, Fund puts them into an agent.',
    agentCalloutTitle: 'Robinhood Chain only.',
    agentCallout:
      'Send USDG, or a Stock Token this agent trades. It lands in the agent’s account, and only your wallet can take it out. Never send ETH to an agent: it cannot hold it.',
    elsewhere: 'Coming from Base, Arbitrum, Ethereum or BNB?',
    elsewhereLink: 'Bridge it in',
  },

  evidence: {
    meta: 'Evidence',
    title: 'Evidence',
    sub: 'Every decision your agents made, its fingerprint, and the transaction that put that fingerprint on chain. Check any of them yourself.',
    facts: 'ON CHAIN',
    network: 'Network',
    networkValue: 'Robinhood Chain mainnet · 4663',
    factory: 'Agent factory',
    operator: 'Shijima’s operator',
    agent: 'Agent account',
    openserv: 'OpenServ agent',
    identity: 'OpenServ ID (Base)',
    copyAll: 'Copy every hash',
    copied: 'Copied',
    step: 'Decision',
    fingerprint: 'Fingerprint',
    explorer: 'On chain',
    open: 'Open ↗',
    check: 'Check it',
    unsealed: 'sealed with the next trade',
    none: 'No decisions yet. The first one appears here with its fingerprint.',
    howTitle: 'How to check one yourself',
    how: [
      'Open a decision: its record is the whole reasoning, in plain words and exact numbers.',
      'Press Check it: your browser rebuilds the fingerprint from that record.',
      'It asks Robinhood Chain for the fingerprint the agent wrote there. They match, or the page says so.',
    ],
  },

  wallet: {
    meta: 'Wallet',
    title: 'Wallet',
    sub: 'Your agents and your own wallet, on Robinhood Chain · read from the chain just now',
    checked: 'CHECKED',
    syncing: 'CHECKING',
    sync: 'Check again',
    agentsEyebrow: 'YOUR AGENTS',
    agentsCount: (n: number) => `${n} AGENT${n === 1 ? '' : 'S'}`,
    noAgents: 'No agent yet',
    noAgentsBody: 'Create one, or copy one that is already running. It starts from $1.',
    split: (cash: string, stocks: string) => `CASH ${cash} · STOCKS ${stocks}`,
    savings: (amount: string) => `${amount} of it earning in savings`,
    flipHint: 'tap for each agent →',
    flipBack: '⟲ tap to flip back',
    eachAgent: 'EACH AGENT',
    cross: 'MOVE\nMONEY',
    walletEyebrow: 'YOUR WALLET · ROBINHOOD CHAIN',
    walletFailed: 'Couldn’t read your wallet from the chain.',
    retry: 'Retry',
    more: (n: number) => `+${n} more`,
    walletTotal: (amount: string) => `${amount} in your wallet`,
    fundAgent: 'Fund an agent',
    needsTitle: (n: number) => `${n} request${n === 1 ? '' : 's'} wait for your answer.`,
    needsOpen: 'Answer',
    unpriced: (symbols: string) =>
      `No price could be read for ${symbols} just now, so the totals leave it out.`,
    actions: {
      fund: 'Fund an agent',
      receive: 'Receive',
      withdraw: 'Withdraw',
      send: 'Send',
      bridge: 'Bridge',
      evidence: 'Evidence',
    },
    seeAll: 'See all',
    noActivity: 'Your agents’ decisions and your money moves appear here.',
    yourAgents: 'Your agents',
    agentSplit: (cash: string, stocks: string, savings: string) =>
      `Cash ${cash} · Stocks ${stocks} · Savings ${savings}`,
    latest: 'LATEST DECISION',
    needs: (n: number) => `${n} WAITING`,
    fromSnapshot: 'last valuation',
  },

  flow: {
    hint: 'Each step opens in your wallet. Keep this tab open until it finishes.',
    relayFills: 'Relay delivers it',
    viewTx: 'View transaction',
    viewRelay: 'Follow it on Relay',
    nothingSent: 'Nothing was sent',
    signTitle: (n: number) => `${n} signature${n === 1 ? '' : 's'} in your wallet.`,
    signBody: 'You see each one before it happens. Nothing moves until you sign.',
    back: 'Back',
    confirm: 'Confirm and sign',
    connectFirst: 'Connect the wallet you signed in with',
    connectToSign: 'Connect your wallet to sign.',
    useFund: 'Fund that agent instead',
    pricing: 'Getting a price…',
  },

  fund: {
    meta: 'Fund an agent',
    title: 'Fund an agent',
    sub: 'Any token, from your wallet or another chain. It lands in your agent as USDG, or as the stock itself.',
    intoWhich: 'Into which agent',
    from: 'From',
    sources: { wallet: 'Your wallet', chain: 'Another chain', anywhere: 'From anywhere' },
    fromWallet: 'FROM YOUR WALLET ON ROBINHOOD CHAIN',
    goesStraight: 'goes straight in',
    swapped: 'swapped to USDG on the way in',
    stockIn: 'goes in as it is, or swapped',
    emptyWallet: 'Your wallet on Robinhood Chain holds nothing to move yet.',
    bringIn: 'Bring money from another chain',
    sourceChain: 'SOURCE CHAIN',
    token: 'TOKEN',
    available: (amount: string, unit: string) => `You hold ${amount} ${unit}`,
    relayNote: 'Relay brings it to Robinhood Chain and hands the agent USDG, usually within a minute.',
    moreThanHeld: (symbol: string) => `That is more ${symbol} than your wallet holds.`,
    nothingHeld: 'Pick what to send.',
    cardTitle: (name: string) => `Into ${name}`,
    review: 'Review',
    done: 'Money is in your agent',
    openAgent: (name: string) => `Open ${name}`,
    anywhereCaption: 'Scan to pay this agent on Robinhood Chain',
    openReceive: 'Open Receive',
    noAgentTitle: 'No agent yet.',
    noAgentBody:
      'Create an agent first: it is the account your money goes into, and only you can take it out.',
    create: 'Create an agent',
  },

  withdraw: {
    meta: 'Withdraw',
    title: 'Withdraw',
    sub: 'From an agent back to your own wallet: the only place its account will pay.',
    fromWhich: 'From which agent',
    what: 'What to take out',
    whats: { cash: 'Cash', stock: 'One stock', everything: 'Everything' },
    cardTitle: (name: string) => `Out of ${name}`,
    toYourWallet: 'TO YOUR WALLET',
    onlyYouTitle: 'To your wallet only.',
    onlyYou: 'The agent’s contract pays its owner and nobody else: not Shijima, not the agent.',
    cashHeld: (cash: string, savings: string | null) =>
      savings
        ? `${cash} in cash, and ${savings} in savings that comes out first when needed`
        : `${cash} in cash`,
    tooMuch:
      'That is more than the agent holds in cash and savings. Take out everything to sell its stocks first.',
    noStocks: 'This agent holds no Stock Tokens right now.',
    whichStock: 'WHICH STOCK',
    how: 'How',
    asIs: 'Take it as it is',
    sellToCash: 'Sell it to cash',
    blankIsAll: 'Leave it empty for all of it',
    sellNote:
      'Selling keeps the cash in the agent, at no worse than 1% under the quote. Take the cash out after.',
    everythingCash: 'As cash, selling first',
    everythingAsIs: 'As it is, stocks and all',
    review: 'Review',
    sendOn: 'Send it on',
    bridgeOut: 'Bridge it out',
    another: 'Something else',
    noAgent: 'No agent to withdraw from yet.',
    words: {
      cash: (amount: string) => `Withdraw $${amount}`,
      everything: (asCash: boolean) =>
        asCash ? 'Withdraw everything as cash' : 'Withdraw everything as it is',
      sell: (symbol: string) => `Sell ${symbol} to cash`,
      stock: (symbol: string) => `Withdraw ${symbol} as it is`,
    },
  },
} as const
