/**
 * Copies the compiled contract ABIs into TypeScript, typed `as const` so viem can infer every call.
 * Run after any contract change: pnpm abis:build   (it runs `forge build` first)
 * The output is generated. Never edit it by hand.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
execFileSync('forge', ['build'], { cwd: resolve(root, 'contracts'), stdio: 'inherit' })

const targets = [
  { artifact: 'Desk.sol/Desk.json', name: 'deskAbi', file: 'desk-abi.ts' },
  { artifact: 'DeskFactory.sol/DeskFactory.json', name: 'deskFactoryAbi', file: 'desk-factory-abi.ts' },
]
for (const t of targets) {
  const { abi } = JSON.parse(readFileSync(resolve(root, 'contracts/out', t.artifact), 'utf8')) as {
    abi: unknown[]
  }
  const body = `// GENERATED by scripts/build-abis.ts from contracts/out/${t.artifact}. Do not edit.\nexport const ${t.name} = ${JSON.stringify(abi, null, 2)} as const\n`
  writeFileSync(resolve(root, 'packages/chain/src/generated', t.file), body)
  console.log(`${t.name}: ${abi.length} entries`)
}
